"""Generate the catalog reference from the catalog itself.

A hand-written inventory of 419 families goes stale the first time someone adds one. This renders
`docs/CATALOG.md` from the specs, so `cli docs` after a catalog change keeps the reference true, and
`tests/test_docs.py` fails the build if it drifts.
"""
from __future__ import annotations

from collections import Counter, defaultdict
from pathlib import Path

from .enrich import geometry_status
from .generators import expand
from .spec import TYPE_CLASSES, FamilySpec

TIER_NOTE = {
    "L200": "box proxy — correct bounding dimensions, no detail",
    "L300": "real parametric solid",
    "L350": "multi-part assembly",
}


def stats(specs: list[FamilySpec]) -> dict:
    types = sum(len(expand(s)) for s in specs)
    return {
        "families": len(specs),
        "types": types,
        "packs": len({s.pack_name for s in specs}),
        "disciplines": len({s.discipline for s in specs}),
        "categories": len({s.category for s in specs}),
        "ifc_classes": len({s.ifc_class for s in specs}),
        "ifc_classes_total": len(TYPE_CLASSES),
        "with_ports": sum(1 for s in specs if s.ports),
        "tiers": dict(Counter(s.tier for s in specs)),
        "mapped": sum(1 for s in specs if s.massing_key),
    }


def render(specs: list[FamilySpec]) -> str:
    st = stats(specs)
    out: list[str] = []
    w = out.append

    w("# Catalog reference\n")
    w("<!-- GENERATED by `python -m massing_families.cli docs` — do not edit by hand. -->\n")
    w(f"**{st['families']} families · {st['types']} types · {st['packs']} packs · "
      f"{st['disciplines']} disciplines · {st['ifc_classes']} of {st['ifc_classes_total']} "
      f"IFC4 type classes**\n")
    w("Every type carries a Uniclass classification, an `MF_Library` provenance pset (key, licence, "
      "version, tier, geometry status) and nominal quantities. Sizes are authored in US imperial "
      "nominals and stored in exact metres.\n")

    w("| | |")
    w("|---|---|")
    w(f"| Geometry tiers | " + ", ".join(
        f"**{k}** {v}" for k, v in sorted(st["tiers"].items())) + " |")
    w(f"| Families with distribution ports | {st['with_ports']} |")
    w(f"| Mapped to a massing built-in | {st['mapped']} |")
    w(f"| Distinct categories | {st['categories']} |")
    w("")
    for tier, note in TIER_NOTE.items():
        if tier in st["tiers"]:
            w(f"- **{tier}** — {note}")
    w("")

    by_disc: dict[str, list[FamilySpec]] = defaultdict(list)
    for s in specs:
        by_disc[s.discipline].append(s)

    w("## Contents\n")
    for disc in sorted(by_disc):
        group = by_disc[disc]
        n = sum(len(expand(s)) for s in group)
        w(f"- [{disc.title()}](#{disc}) — {len(group)} families, {n} types")
    w("")

    for disc in sorted(by_disc):
        group = sorted(by_disc[disc], key=lambda s: (s.category, s.label))
        n = sum(len(expand(s)) for s in group)
        w(f"\n## {disc}\n")
        w(f"{len(group)} families · {n} types · packs: "
          + ", ".join(f"`{p}`" for p in sorted({s.pack_name for s in group})) + "\n")
        w("| Family | IFC class | Tier | Geometry | Types | Uniclass | Ports |")
        w("|---|---|---|---|--:|---|:-:|")
        for s in group:
            code = s.classification.get("uniclass", "—")
            ports = "✓" if s.ports else ""
            w(f"| **{s.label}** <br>`{s.key}` | `{s.ifc_class}` | {s.tier} | "
              f"{geometry_status(s)} | {len(expand(s))} | `{code}` | {ports} |")
    w("")
    return "\n".join(out)


def write(specs: list[FamilySpec], root: Path) -> Path:
    path = Path(root) / "docs" / "CATALOG.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(specs), encoding="utf-8")
    return path
